version=1.0.0
description=ReportPortal template plugin, ported to the develop branch package layout.
pluginId = template
pluginClass=com.epam.reportportal.extension.template.TemplatePlugin
pluginName = Template Plugin
provider = ReportPortal
license = Apache 2.0
isIntegrationsAllowed = true
isEmbedded = false
isMultiple = false
